# Generated by Django 3.0.3 on 2020-08-04 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('access_token', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('class_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(default='student', max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('class_enrolled', models.ManyToManyField(blank=True, default=None, related_name='enrolledClasses', to='core_api.Class')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assigned', to='core_api.Class')),
            ],
        ),
        migrations.CreateModel(
            name='userClassRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.Class')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.UserAccount')),
            ],
        ),
    ]
