# Generated by Django 3.0.3 on 2020-08-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='class_name',
        ),
    ]
