# Generated by Django 3.0.3 on 2020-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_remove_useraccount_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pr', models.CharField(max_length=10)),
                ('lesson_name', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=30)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
                ('pdf', models.FileField(default='Doc/None/No-pdf.pdf', upload_to='Doc/')),
                ('aud', models.FileField(default='Audio/None/No-audio.3gp', upload_to='Audio/')),
                ('vdo', models.FileField(default='Doc/None/No-video.mp4', upload_to='Video/')),
            ],
        ),
        migrations.DeleteModel(
            name='userClassRelation',
        ),
        migrations.AddField(
            model_name='class',
            name='lesson_attached',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.lessons'),
        ),
    ]
