# Generated by Django 3.0.3 on 2020-08-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20200810_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=30)),
                ('text_lesson', models.CharField(max_length=30)),
                ('image_stu', models.ImageField(default='Images/None/No-img.jpg', upload_to='Student_Images_lesson/')),
                ('pdf_stu', models.FileField(default='Doc/None/No-pdf.pdf', upload_to='student_Doc/')),
                ('aud_stu', models.FileField(default='Audio/None/No-audio.3gp', upload_to='student_Audio/')),
                ('submitted_by', models.CharField(max_length=30)),
            ],
        ),
    ]
