# Generated by Django 3.0.3 on 2020-08-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='aud',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='vdo',
        ),
    ]
