# Generated by Django 3.0.3 on 2020-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20200821_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='less_aud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud', models.FileField(default='Audio/None/No-audio.3gp', upload_to='Audio/')),
            ],
        ),
        migrations.CreateModel(
            name='less_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='less_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(default='Doc/None/No-pdf.pdf', upload_to='Doc/')),
            ],
        ),
        migrations.CreateModel(
            name='less_vdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdo', models.FileField(default='Video/None/No-video.mp4', upload_to='Video/')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='aud_attached',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.less_aud'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='imgAttached',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.less_img'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='pdf_attached',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.less_pdf'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='vdo_attached',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.less_vdo'),
        ),
    ]
