# Generated by Django 3.0.3 on 2020-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_auto_20200825_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='audByStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_stu', models.FileField(default='Audio/None/No-audio.3gp', upload_to='student_Audio/')),
            ],
        ),
        migrations.CreateModel(
            name='imageByStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_stu', models.ImageField(default='Images/None/No-img.jpg', upload_to='Student_Images_lesson/')),
            ],
        ),
        migrations.CreateModel(
            name='pdfByStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_stu', models.FileField(default='Doc/None/No-pdf.pdf', upload_to='student_Doc/')),
            ],
        ),
    ]
