# Generated by Django 3.0.3 on 2020-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_auto_20200825_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('Batch_attached', models.ManyToManyField(blank=True, default=None, to='core_api.Class')),
            ],
        ),
    ]
