# Generated by Django 3.0.3 on 2020-09-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
