# Generated by Django 3.0.3 on 2020-09-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_class_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='class_enrolled',
        ),
    ]
