# Generated by Django 3.0.3 on 2020-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_remove_useraccount_class_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='users_enrolled',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.UserAccount'),
        ),
    ]
