# Generated by Django 3.0.3 on 2020-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_class_users_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='users_enrolled',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='class_enrolled',
            field=models.ManyToManyField(blank=True, default=None, related_name='enrolledClasses', to='core_api.Class'),
        ),
    ]
