# Generated by Django 3.0.3 on 2020-09-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_less_img_imna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='less_img',
            name='imna',
        ),
    ]
