# Generated by Django 2.1 on 2020-09-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0016_remove_less_img_imna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='class_enrolled',
        ),
    ]
