# Generated by Django 2.1 on 2020-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0017_remove_useraccount_class_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_enrolled',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.UserAccount'),
        ),
    ]
