# Generated by Django 2.1 on 2020-09-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0018_class_student_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Batch_attached',
        ),
    ]
