# Generated by Django 2.1 on 2020-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0022_less_img_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='less_aud',
            name='aud_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='less_pdf',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='less_vdo',
            name='vdo_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
