# Generated by Django 2.1 on 2020-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0023_auto_20200914_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='student_enrolled',
            field=models.ManyToManyField(blank=True, default=None, to='core_api.UserAccount'),
        ),
    ]
