# Generated by Django 2.1 on 2020-10-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0024_lessons_student_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='aud_attached',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='id_pr',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='imgAttached',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='pdf_attached',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='vdo_attached',
        ),
    ]
