# Generated by Django 2.1 on 2020-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0025_auto_20201003_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='scn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scn_name', models.CharField(max_length=30)),
                ('Scn_desc', models.CharField(max_length=30)),
                ('image', models.ImageField(default='images/None/No-img.jpg', upload_to='images/')),
                ('pdf', models.FileField(default='pdfs/None/No-pdf.pdf', upload_to='pdfs/')),
                ('audio', models.FileField(default='ados/None/No-pdf.3gp', upload_to='ados/')),
                ('video', models.FileField(default='videos/None/No-pdf.mp4', upload_to='videos/')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='screen',
            field=models.ManyToManyField(related_name='cd', to='core_api.scn'),
        ),
    ]
