# Generated by Django 2.1 on 2020-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0026_auto_20201003_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='student_enrolled',
            field=models.ManyToManyField(blank=True, default=None, related_name='entry', to='core_api.UserAccount'),
        ),
    ]
