# Generated by Django 2.1 on 2020-10-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0027_auto_20201007_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student_enrolled',
        ),
    ]
