# Generated by Django 2.1 on 2020-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_api', '0001_initial'),
        ('core_api', '0028_remove_class_student_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='nm',
            field=models.ManyToManyField(related_name='c', to='help_api.name'),
        ),
    ]
