# Generated by Django 2.1 on 2020-10-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0029_lessons_nm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='lesson_attached',
        ),
    ]
