# Generated by Django 2.1 on 2020-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0030_auto_20201008_1751'),
        ('help_api', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='class_enrolled',
            field=models.ManyToManyField(blank=True, default=None, related_name='enrolledClasses', to='help_api.Class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
