# Generated by Django 2.1 on 2020-10-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0030_auto_20201008_1751'),
        ('help_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('class_address', models.CharField(max_length=200)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectadd', to='core_api.Subject')),
                ('lesson_attached', models.ManyToManyField(blank=True, default=None, to='core_api.lessons')),
            ],
        ),
    ]
